# Use official Node.js LTS image
FROM node:22
# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if you have them)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Expose port 30001
EXPOSE 3000

# Start the worker
CMD ["node", "index.js"]
